version: '3.8'

services:
  stock_pick_game:
    image: ghcr.io/loganrenz/stock-pick-game:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=4556
      - DATABASE_URL=file:/data/dev.db
      - DATABASE_PROVIDER=sqlite
    ports:
      - "4556:4556"
      - "5173:5173"
    volumes:
      - ./data:/data:rw
    restart: always

networks:
  default:
    driver: bridge 