version: '3.8'

services:
  stock_pick_db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_pick_game
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stock_pick_network

  stock_pick_backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    working_dir: /app
    environment:
      - NODE_ENV=development
      - PORT=4556
    env_file:
      - ./backend/.env_file
    ports:
      - "4556:4556"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - stock_pick_db
    networks:
      - stock_pick_network

  stock_pick_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - stock_pick_backend
    networks:
      - stock_pick_network

volumes:
  pgdata:

networks:
  stock_pick_network:
    driver: bridge 