version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stock-pick-game-dev
    ports:
      - "8081:8081"
      - "5173:5173"
    env_file:
      - .env
    volumes:
      # Mount source code for hot-reloading, excluding node_modules
      - .:/app
      - /app/node_modules
      # Persist data and logs using named volumes
      - stock-pick-game-data:/app/data
      - stock-pick-game-logs:/app/logs
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=8081
      - FRONTEND_URL=http://localhost:5173
      - DATABASE_URL=file:/app/data/stock-pick-game.db
      - JWT_SECRET=a-secure-secret-for-development

volumes:
  stock-pick-game-data:
  stock-pick-game-logs: 