version: '3.8'

services:
  stock_pick_db:
    container_name: stock-pick-game-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock_pick_game
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - stock_pick_network

  stock_pick_backend:
    container_name: stock-pick-game-backend
    image: ghcr.io/loganrenz/stock-pick-game:latest
    environment:
      - NODE_ENV=production
      - PORT=4556
    ports:
      - "4556:4556"
    depends_on:
      - stock_pick_db
    networks:
      - stock_pick_network

  stock_pick_frontend:
    container_name: stock-pick-game-frontend
    image: ghcr.io/loganrenz/stock-pick-game-frontend:latest
    ports:
      - "5173:5173"
    depends_on:
      - stock_pick_backend
    networks:
      - stock_pick_network

volumes:
  pgdata:

networks:
  stock_pick_network:
    driver: bridge 